In [1]:
import pandas as pd
import numpy as np

In [2]:
files = ['data-1.csv','data-2.csv','data-3.csv','data-4.csv','data-5.csv','data-6.csv']

In [3]:
class Stats:
    def __init__(self, data):
        self.std = np.std(data)
        self.mean = np.mean(data)
        self.min = np.min(data)
        self.max = np.max(data)
    def __str__(self):
        res = ""
        res += "Standard deviation: " + str(self.std)
        res += "\nMean: " + str(self.mean)
        res += "\nMin: " + str(self.min)
        res += "\nMax: " + str(self.max)
        return res

In [4]:
data = [pd.read_csv(x) for x in files]

In [5]:
stats = [(Stats(d.x), Stats(d.y), np.corrcoef(d.x, d.y)) for d in data]

In [6]:
for i in range(len(files)):
    print("\nStats for file:", files[i])
    print("==X==")
    print(str(stats[i][0]))
    print("==Y==")
    print(str(stats[i][1]))
    print("Correlation coefficient:\n", stats[i][2])


Stats for file: data-1.csv
==X==
Standard deviation: 12.094586936598956
Mean: 8.71769618641382
Min: -22.635877790008944
Max: 35.23705548785129
==Y==
Standard deviation: 6.606680770370137
Mean: 12.522874034702584
Min: -2.5650878326932127
Max: 27.38415261152477
Correlation coefficient:
 [[1.        0.9503257]
 [0.9503257 1.       ]]

Stats for file: data-2.csv
==X==
Standard deviation: 11.424031427941332
Mean: -0.7107871267159573
Min: -33.2711130771198
Max: 27.6470003722073
==Y==
Standard deviation: 6.226549791205469
Mean: -0.7489869764497991
Min: -18.621803760419066
Max: 14.147314992317481
Correlation coefficient:
 [[1.         0.95515317]
 [0.95515317 1.        ]]

Stats for file: data-3.csv
==X==
Standard deviation: 2.2318288211623565
Mean: 0.9689074904200939
Min: -2.4490643296742807
Max: 4.51888491755363
==Y==
Standard deviation: 1.1473837107336813
Mean: 8.508535236641327
Min: 6.641734490391762
Max: 10.551871022804317
Correlation coefficient:
 [[1.         0.98193726]
 [0.98193726 1